[package]
name = "emsgine-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emsgine-lib = { path = "../emsgine-lib" }
ihex = "3.0"
lazy_static = "1.4.0"
chain-cmp = "0.2.0"
