// generated-code: 2023-05-27T11:50:23.500925

#[derive(Debug)]
pub enum AvrInstructionSet {
    AddWithCarry, //bra bla
    Compare, //bra bla
    CompareSkipIfEqual, //bra bla
    SubtractWithoutCarry, //bra bla
    Add, //bra bla
    CompareWithCarry, //bra bla
    FractionalMultiplyUnsigned, //bra bla
    MultiplySignedWithUnsigned, //bra bla
    FractionalMultiplySigned, //bra bla
    FractionalMultiplySignedWithUnsigned, //bra bla
    CopyRegisterWord, //bra bla
    MultiplySigned, //bra bla
    NoOperation, //bra bla
    SubtractWithCarry, //bra bla
    AddWithImmediate, //bra bla
    SubtractImmediateWord, //bra bla
    ArithmeticShiftRight, //bra bla
    BitClearInSREG, //bra bla
    Break, //bra bla
    ExtendedLoadProgramMemory, //bra bla
    LoadProgramMemory, //bra bla
    Sleep, //bra bla
    StoreMemoryProgram, //bra bla
    StoreMemoryProgramPostIncrementZ, //bra bla
    WatchdogReset, //bra bla
    BitSet, //bra bla
    ExtendedIndirectJump, //bra bla
    IndirectJump, //bra bla
    ExtendedIndirectCallSubroutine, //bra bla
    ReturnFromInterrupt, //bra bla
    IndirectCallSubroutine, //bra bla
    ReturnFromSubroutine, //bra bla
    Call, //bra bla
    Complement, //bra bla
    ComplementTwo, //bra bla
    Decrement, //bra bla
    DataEncryptionStandart, //bra bla
    Increment, //bra bla
    SwapNibbles, //bra bla
    Jump, //bra bla
    LogicalShiftRight, //bra bla
    RotateRightThroughCarry, //bra bla
    ClearIOBit, //bra bla
    SetBitIoSpace, //bra bla
    SkipIfIoBitCleared, //bra bla
    SkipIfIoBitSet, //bra bla
    ExtendedLoadProgramMemoryZ, //bra bla
    ExtendedLoadProgramMemoryZplus, //bra bla
    LoadIndirectFromDataSpaceIndexX, //bra bla
    LoadIndirectFromDataSpacePostIncrementX, //bra bla
    LoadIndirectFromDataSpacePreDecrementX, //bra bla
    LoadIndirectFromDataSpacePostIncrementY, //bra bla
    LoadIndirectFromDataSpacePreDecrementY, //bra bla
    LoadIndirectFromDataSpacePostIncrementZ, //bra bla
    LoadIndirectFromDataSpacePreDecrementZ, //bra bla
    LoadDirectFromDataSpace, //bra bla
    LoadProgramMemoryZ, //bra bla
    LoadProgramMemoryZplus, //bra bla
    PopRegisterFromStack, //bra bla
    LoadAndClear, //bra bla
    LoadAndSet, //bra bla
    LoadAndToggle, //bra bla
    PushRegisterToStack, //bra bla
    StoreIndirectDataSpaceIndexX, //bra bla
    StoreIndirectDataSpacePostIncrementX, //bra bla
    StoreIndirectDataSpacePreDecrementX, //bra bla
    StoreIndirectDataSpacePostIncrementY, //bra bla
    StoreIndirectDataSpacePreDecrementY, //bra bla
    StoreIndirectDataSpacePostIncrementZ, //bra bla
    StoreIndirectDataSpacePreDecrementZ, //bra bla
    StoreDirectDataSpace, //bra bla
    Exchange, //bra bla
    MultiplyUnsigned, //bra bla
    LogicalAnd, //bra bla
    LogicalExclusiveOr, //bra bla
    CopyRegister, //bra bla
    LogicalOr, //bra bla
    LogicalAndWithImmediate, //bra bla
    BitLoadInRegisterfromT, //bra bla
    BitStorefromRegister, //bra bla
    BranchSregBitCleared, //bra bla
    BranchSregBitSet, //bra bla
    SkipIfBitCleared, //bra bla
    SkipIfBitSet, //bra bla
    CompareWithImmediate, //bra bla
    LoadFromIOSpace, //bra bla
    StoreToIoSpace, //bra bla
    LoadImmediate, //bra bla
    LogicalOrWithImmediate, //bra bla
    RelativeCallSubroutine, //bra bla
    RelativeJump, //bra bla
    SubtractImmediateWithCarrySbi, //bra bla
    SubtractImmediate, //bra bla
    LoadIndirectWithDisplacementY, //bra bla
    StoreIndirectWithDisplacementY, //bra bla
    LoadIndirectWithDisplacementZ, //bra bla
    StoreIndirectWithDisplacementZ, //bra bla
    LoadStoreIndirectWithHightDisplacement, //bra bla
    Invalid
}
